### ISSUE TITLE
Local create image and image create with this workflow, behave differently [Question]

### ISSUE THREAD

**Issue by 0nary** [docker/build-push-action#702]
#### Steps to reproduce this issue

I'm not sure how to reproduce.

#### Expected behaviour

I expeted an image a create with :
```
docker build -t docker-image . -f ./src/project/Dockerfile
```
will behave the same as the image created with :
```
name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          file: './src/project/Dockerfile'
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

```
#### Actual behaviour

But with the workflow image I get an exception : 
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at RazorLight.Compilation.RoslynCompilationService.CompileAndEmit(IGeneratedRazorTemplate razorTemplate)
   at RazorLight.Compilation.RazorTemplateCompiler.CompileAndEmit(RazorLightProjectItem projectItem)
   at RazorLight.Compilation.RazorTemplateCompiler.OnCacheMissAsync(String templateKey)
```
I don't have with the local one.

### Question

So my question is, what changes between :
```
docker build -t docker-image . -f ./src/project/Dockerfile
```
and : 
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at RazorLight.Compilation.RoslynCompilationService.CompileAndEmit(IGeneratedRazorTemplate razorTemplate)
   at RazorLight.Compilation.RazorTemplateCompiler.CompileAndEmit(RazorLightProjectItem projectItem)
   at RazorLight.Compilation.RazorTemplateCompiler.OnCacheMissAsync(String templateKey)
```
?

I run the local command on a windows computer.

If this question has been already been answered may a suggest to adding it to the Troubleshooting or refer it in the readme.md .

**Comment by crazy-max** [comment]
Can you post your Dockerfile, `docker info` output and complete build logs please?

**Comment by 0nary** [comment]
Dockerfile:
```
#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80
RUN apt-get update
RUN apt-get install wkhtmltopdf -y

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["src/Souche.Api/Souche.Api.csproj", "src/Souche.Api/"]
COPY ["src/Souche.Application/Souche.Application.csproj", "src/Souche.Application/"]
COPY ["src/Souche.Domain/Souche.Domain.csproj", "src/Souche.Domain/"]
COPY ["src/Souche.Integration/Souche.Integration.csproj", "src/Souche.Integration/"]
COPY ["src/Souche.WebUI/Souche.WebUI.csproj", "src/Souche.WebUI/"]
RUN dotnet restore "src/Souche.Api/Souche.Api.csproj"
COPY . .
WORKDIR "/src/src/Souche.Api"
RUN dotnet build "Souche.Api.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Souche.Api.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Souche.Api.dll"]
```
docker info output:

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.8.2)
  compose: Docker Compose (Docker Inc., v2.7.0)
  extension: Manages Docker extensions (Docker Inc., v0.2.8)
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc., 0.6.0)
  scan: Docker Scan (Docker Inc., v0.17.0)

Server:
 Containers: 6
  Running: 0
  Paused: 0
  Stopped: 6
 Images: 27
 Server Version: 20.10.17
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2 io.containerd.runtime.v1.linux
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 10c12954828e7c7c9b6e0ea9b0c02b01407d3ae1
 runc version: v1.1.2-0-ga916309
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.4.72-microsoft-standard-WSL2
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 24.88GiB
 Name: docker-desktop
 ID: E4XQ:NDBB:JTDD:ZULX:B2I7:KBK6:RMAG:7ENF:HJ2X:ZFAR:L4KN:CR2R
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5000
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support
```

docker build logs: 
```
PS C:\Users\User\source\repos\neuroglia-io\souche.be\deployment\docker-compose> cd C:\Users\User\source\repos\neuroglia-io\souche.be
PS C:\Users\User\source\repos\neuroglia-io\souche.be> docker build -t souche-test:latest . -f ./src/Souche.Api/Dockerfile
[+] Building 0.4s (24/24) FINISHED
 => [internal] load build definition from Dockerfile                                                                                                                                                                                                                      0.1s
 => => transferring dockerfile: 32B                                                                                                                                                                                                                                       0.0s
 => [internal] load .dockerignore                                                                                                                                                                                                                                         0.1s
 => => transferring context: 35B                                                                                                                                                                                                                                          0.0s
 => [internal] load metadata for mcr.microsoft.com/dotnet/sdk:6.0                                                                                                                                                                                                         0.2s
 => [internal] load metadata for mcr.microsoft.com/dotnet/aspnet:6.0                                                                                                                                                                                                      0.0s
 => [build  1/11] FROM mcr.microsoft.com/dotnet/sdk:6.0@sha256:2fdad630a59fbdecbfcc6aaf3ccae96eea0e8d24cd4607669fde0de107a94c53                                                                                                                                           0.0s
 => [internal] load build context                                                                                                                                                                                                                                         0.1s
 => => transferring context: 43.50kB                                                                                                                                                                                                                                      0.1s
 => [base 1/4] FROM mcr.microsoft.com/dotnet/aspnet:6.0                                                                                                                                                                                                                   0.0s
 => CACHED [base 2/4] WORKDIR /app                                                                                                                                                                                                                                        0.0s
 => CACHED [base 3/4] RUN apt-get update                                                                                                                                                                                                                                  0.0s
 => CACHED [base 4/4] RUN apt-get install wkhtmltopdf -y                                                                                                                                                                                                                  0.0s
 => CACHED [final 1/2] WORKDIR /app                                                                                                                                                                                                                                       0.0s
 => CACHED [build  2/11] WORKDIR /src                                                                                                                                                                                                                                     0.0s
 => CACHED [build  3/11] COPY [src/Souche.Api/Souche.Api.csproj, src/Souche.Api/]                                                                                                                                                                                         0.0s
 => CACHED [build  4/11] COPY [src/Souche.Application/Souche.Application.csproj, src/Souche.Application/]                                                                                                                                                                 0.0s
 => CACHED [build  5/11] COPY [src/Souche.Domain/Souche.Domain.csproj, src/Souche.Domain/]                                                                                                                                                                                0.0s
 => CACHED [build  6/11] COPY [src/Souche.Integration/Souche.Integration.csproj, src/Souche.Integration/]                                                                                                                                                                 0.0s
 => CACHED [build  7/11] COPY [src/Souche.WebUI/Souche.WebUI.csproj, src/Souche.WebUI/]                                                                                                                                                                                   0.0s
 => CACHED [build  8/11] RUN dotnet restore "src/Souche.Api/Souche.Api.csproj"                                                                                                                                                                                            0.0s
 => CACHED [build  9/11] COPY . .                                                                                                                                                                                                                                         0.0s
 => CACHED [build 10/11] WORKDIR /src/src/Souche.Api                                                                                                                                                                                                                      0.0s
 => CACHED [build 11/11] RUN dotnet build "Souche.Api.csproj" -c Release -o /app/build                                                                                                                                                                                    0.0s
 => CACHED [publish 1/1] RUN dotnet publish "Souche.Api.csproj" -c Release -o /app/publish                                                                                                                                                                                0.0s
 => CACHED [final 2/2] COPY --from=publish /app/publish .                                                                                                                                                                                                                 0.0s
 => exporting to image                                                                                                                                                                                                                                                    0.0s
 => => exporting layers                                                                                                                                                                                                                                                   0.0s
 => => writing image sha256:66ce89fcc3bfba9abb49069e2ae5cee95c680b783089621745c1b48400bffd58                                                                                                                                                                              0.0s
 => => naming to docker.io/library/souche-test:latest
```

**Comment by crazy-max** [comment]
Thanks but for logs I mean ones from the GitHub workflow with the exception.

**Comment by 0nary** [comment]
The github workflow doesn't throw an exception. It's when I use the image , create by the github workflow, I get an exception when performing an action and this doesn't append with the image I creates locally.

You can fine the logs in this file :
[workflow-logs.txt](https://github.com/docker/build-push-action/files/9747317/workflow-logs.txt)

**Comment by crazy-max** [comment]
Don't think that's an issue with this action or buildx but your project. My best guess is that dome files copied locally with `COPY . .` are not available in your repository.

You can repro locally with:

```console
docker build -t docker-image -f ./src/project/Dockerfile <git-repo>
```

Where `<git-repo>` is the Git URL to your repository like `https://github.com/user/repo.git`.

**Comment by 0nary** [comment]
Yes my repo is private.
I will try this, thanks.

**Comment by 0nary** [comment]
I'm struggling to use your command `docker build -t docker-image https://github.com/<user>/<repo>.git#:src/project`

I will use a one of my public test repos (even if i don't think this one will face the same issue), so you can say esealy where I'm wrong whit your command.
I use the repos : `https://github.com/0nary/test.in.docker`.
Where the Dockerfile is at `/src/Example.Service/Dockerfile`.
And the main branch is `master`.

So the docker command should be : 
```
docker build -t docker-image https://github.com/0nary//0nary/test.in.docker.git#master:src/Example.Service
```
But then I get `failed to solve with frontend dockerfile.v0: failed to read dockerfile: failed to load cache key: subdir not supported yet`.

And if I remove the folder part : 
```
docker build -t docker-image https://github.com/0nary//0nary/test.in.docker.git#master:
```
I get `failed to solve with frontend dockerfile.v0: failed to read dockerfile: failed to load cache key: failed to fetch remote https://github.com/0nary//0nary/test.in.docker.git: exit status 128`

**Comment by crazy-max** [comment]
Subdirectory for Git context is available from [BuildKit v0.9.0](https://github.com/moby/buildkit/releases/tag/v0.9.0). If you're using the `docker` builder, then BuildKit in Docker Engine will be used. As Docker Engine < v22.x.x embeds Buildkit 0.8.2 at the moment, it does not support this feature. So you have to create first a `docker-container` builder:

```console
$ docker buildx create --name mybuilder --use --bootstrap
$ docker buildx build --load -t docker-image https://github.com/<user>/<repo>.git#:src/project
```

**Comment by 0nary** [comment]
Thanks.
So the command when:
- the repos is `https://github.com/0nary/test.in.docker`.
- the Dockerfile is at `/src/Example.Service/Dockerfile`.
- the main branch is `master`.
```
$ docker buildx create --name mybuilder --use --bootstrap
$  docker buildx build --load -t docker-image https://github.com/0nary/test.in.docker.git#master: -f src/Example.Service/Dockerfile
```

And I have the same issue.

So it likely your guess is correct 

> Don't think that's an issue with this action or buildx but your project. My best guess is that some files copied locally with `COPY . .` are not available in your repository.

I will investigate, thanks.

**Comment by 0nary** [comment]
So I found where come from the problem even if I don't understand why this append.

In a razor template (invoice.cshtml), I have this code : 
```

@model Souche.Application.Models.InvoiceTemplateModel
@{
    System.DateTime sendAt = System.DateTime.MinValue;
    sendAt =
        Model.Invoice.SentAt.HasValue ?
        (Model.Invoice.SentAt.Value.ToOffset(new System.TimeSpan(2, 0, 0)).DateTime.IsDaylightSavingTime() ?
            Model.Invoice.SentAt.Value.ToOffset(new System.TimeSpan(1, 0, 0)).DateTime :
            Model.Invoice.SentAt.Value.ToOffset(new System.TimeSpan(2, 0, 0)).DateTime)
        :
        (System.DateTime.Now.IsDaylightSavingTime() ?
            System.DateTimeOffset.Now.ToOffset(new System.TimeSpan(1, 0, 0)).DateTime :
            System.DateTimeOffset.Now.ToOffset(new System.TimeSpan(2, 0, 0)).DateTime);
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" crossorigin="anonymous">
</head>
<body>
            <div>Date de facturation: <span>@sendAt.ToString("dd/MM/yyyy")</span></div>
</body>
</html>

```

And for some reason this code throws a null ref exception at `@sendAt.ToString("dd/MM/yyyy")`, when a build the docker image from the github repository, but not when a build the image from my local repository.

**Comment by 0nary** [comment]
To solve this I change my code from this:
```
@model Souche.Application.Models.InvoiceTemplateModel
@{
    System.DateTime sendAt =
        Model.Invoice.SentAt.HasValue ?
        (Model.Invoice.SentAt.Value.ToOffset(new System.TimeSpan(2, 0, 0)).DateTime.IsDaylightSavingTime() ?
            Model.Invoice.SentAt.Value.ToOffset(new System.TimeSpan(1, 0, 0)).DateTime :
            Model.Invoice.SentAt.Value.ToOffset(new System.TimeSpan(2, 0, 0)).DateTime)
        :
        (System.DateTime.Now.IsDaylightSavingTime() ?
            System.DateTimeOffset.Now.ToOffset(new System.TimeSpan(1, 0, 0)).DateTime :
            System.DateTimeOffset.Now.ToOffset(new System.TimeSpan(2, 0, 0)).DateTime);
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" crossorigin="anonymous">
</head>
<body>
            <div>Date de facturation: <span>@sendAt.ToString("dd/MM/yyyy")</span></div>
</body>
</html>
```
to this : 
```
@model Souche.Application.Models.InvoiceTemplateModel
@{
    System.DateTime sendAt =  new System.DateTime();
    sendAt =
        Model.Invoice.SentAt.HasValue ?
        (Model.Invoice.SentAt.Value.ToOffset(new System.TimeSpan(2, 0, 0)).DateTime.IsDaylightSavingTime() ?
            Model.Invoice.SentAt.Value.ToOffset(new System.TimeSpan(1, 0, 0)).DateTime :
            Model.Invoice.SentAt.Value.ToOffset(new System.TimeSpan(2, 0, 0)).DateTime)
        :
        (System.DateTime.Now.IsDaylightSavingTime() ?
            System.DateTimeOffset.Now.ToOffset(new System.TimeSpan(1, 0, 0)).DateTime :
            System.DateTimeOffset.Now.ToOffset(new System.TimeSpan(2, 0, 0)).DateTime);
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" crossorigin="anonymous">
</head>
<body>
            <div>Date de facturation: <span>@sendAt.ToString("dd/MM/yyyy")</span></div>
</body>
</html>
```
Don't really know why it works , but it works.
